server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /api/aviation/ {
        proxy_pass http://api.aviationstack.com/v1/;
        proxy_http_version 1.1;
        proxy_set_header Host api.aviationstack.com;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
